SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VehicleStatus](
    [StatusId] [int] IDENTITY(1,1) NOT NULL,
    [STATUS] [varchar](15) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VehicleStatus] ADD PRIMARY KEY CLUSTERED 
(
    [StatusId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
