SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarColours](
    [CarColourId] [int] IDENTITY(1,1) NOT NULL,
    [Colour] [nvarchar](20) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CarColours] ADD  CONSTRAINT [PK_CarColour_ColourId] PRIMARY KEY CLUSTERED 
(
    [CarColourId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[CarColours] ADD  CONSTRAINT [UNIQUE_CarColour] UNIQUE NONCLUSTERED 
(
    [Colour] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO