SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EngineSize](
    [EngineSizeId] [int] IDENTITY(1,1) NOT NULL,
    [EngineSize] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EngineSize] ADD PRIMARY KEY CLUSTERED 
(
    [EngineSizeId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO