SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Salutation](
    [SalutationId] [int] IDENTITY(1,1) NOT NULL,
    [Name] [nvarchar](20) NULL,
    [Registered] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Salutation] ADD  CONSTRAINT [PK_Salutation_SalutationId] PRIMARY KEY CLUSTERED 
(
    [SalutationId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[Salutation] ADD  CONSTRAINT [UNIQUE_SalutationName] UNIQUE NONCLUSTERED 
(
    [Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO