SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarManuFacturers](
    [ManufacturerID] [bigint] IDENTITY(1,1) NOT NULL,
    [Manufacturer] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CarManuFacturers] ADD PRIMARY KEY CLUSTERED 
(
    [ManufacturerID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[CarManuFacturers] ADD  CONSTRAINT [UNIQUE_Manufacturer] UNIQUE NONCLUSTERED 
(
    [Manufacturer] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO