SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarFuelTypes](
    [FuelTypeId] [int] IDENTITY(1,1) NOT NULL,
    [Fuel] [nvarchar](15) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CarFuelTypes] ADD  CONSTRAINT [PK_FuelTypeID] PRIMARY KEY CLUSTERED 
(
    [FuelTypeId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[CarFuelTypes] ADD  CONSTRAINT [UNIQUE_CarFuelType] UNIQUE NONCLUSTERED 
(
    [Fuel] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
